- name: Ensure necessary packages are installed
  package:
    name:
      - icaclient
      - xclip
    state: present
  become: true

- name: Create custom systemd service units for Citrix processes
  template:
    src: citrix_service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  loop: "{{ citrix_services }}"
  become: true

- name: Reload systemd to recognize new service units
  systemd:
    daemon_reload: yes
  become: true

- name: Start and enable Citrix service units
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  loop: "{{ citrix_services }}"
  become: true

- name: Restart Citrix Workspace services
  systemd:
    name: "{{ item.name }}"
    state: restarted
    enabled: yes
  loop: "{{ citrix_services }}"
  become: true