---
- name: Ensure that llvm is installed
  community.general.pacman:
    name:
    - llvm
    - llvm-libs
    state: latest
    update_cache: true
  become: true
  notify:
  - refresh shared lib cache with ldconfig

- name: Check LLVM installation
  command: llvm-config --version
  register: llvm_version
  changed_when: false

- name: Display LLVM version
  debug:
    var: llvm_version.stdout

- name: Verify Clang can run
  command: clang --version
  register: clang_version
  changed_when: false

- name: Display Clang version
  debug:
    var: clang_version.stdout