---
- name: Refresh gpg key for python38 in AUR
  ansible.builtin.command:
    cmd: gpg --keyserver keyserver.ubuntu.com --recv-keys E3FF2839C048B25C084DEBE9B26995E310250568

- name: Install Python 3.8
  kewlfft.aur.aur:
    name: python38
